#!/usr/bin/env python3
"""Generate and check hash-locked build environments for packages/python/*.

Each package gets a ``requirements-build.lock`` that pins, with SHA-256
hashes, everything the publish workflow installs before it builds and
tests the package:

* the package's ``[build-system].requires`` (setuptools, wheel, ...)
* the package's runtime ``dependencies``
* the package's ``[test]`` extra
* the build front-end (``build``) and SBOM generator (``cyclonedx-bom``)

The publish workflow installs this file with ``pip install --require-hashes``
and then builds with ``--no-isolation``, so nothing reaches the build
environment that is not named and hashed in the repository. This closes the
gap that build-provenance attestation does not cover: attestation proves our
workflow produced the wheel, not that the build environment was clean.

Modes
-----
``lock``          resolve with uv and write the lock (needs ``uv`` on PATH)
``check-inputs``  stdlib only; verify the lock was generated from the current
                  pyproject inputs (used in CI, no network, no uv)

Usage
-----
    python .github/scripts/lock_build_env.py lock --all
    python .github/scripts/lock_build_env.py lock hummbl-governance base120
    python .github/scripts/lock_build_env.py check-inputs --all
    python .github/scripts/lock_build_env.py check-inputs hummbl-governance
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGES_DIR = REPO_ROOT / "packages" / "python"
LOCK_NAME = "requirements-build.lock"
INPUTS_HASH_PREFIX = "# inputs-sha256: "
PYTHON_VERSION = "3.13"
PYTHON_PLATFORM = "linux"

# Tools the publish workflow needs in the build job beyond the package's
# own requirements. Keep this list short; every entry is hashed per package.
BUILD_TOOLS = ("build>=1.0", "cyclonedx-bom>=5.0")


def package_dirs(names: list[str] | None) -> list[Path]:
    if names:
        dirs = [PACKAGES_DIR / n for n in names]
        missing = [d for d in dirs if not (d / "pyproject.toml").is_file()]
        if missing:
            sys.exit(f"no pyproject.toml in: {', '.join(str(m) for m in missing)}")
        return dirs
    return sorted(d for d in PACKAGES_DIR.iterdir() if (d / "pyproject.toml").is_file())


def lock_inputs(pkg_dir: Path) -> list[str]:
    """The exact requirement strings the lock must cover, sorted and deduped."""
    data = tomllib.loads((pkg_dir / "pyproject.toml").read_text(encoding="utf-8"))
    project = data.get("project", {})
    reqs: set[str] = set()
    reqs.update(data.get("build-system", {}).get("requires", []))
    reqs.update(project.get("dependencies", []))
    reqs.update(project.get("optional-dependencies", {}).get("test", []))
    reqs.update(BUILD_TOOLS)
    return sorted(r.strip() for r in reqs if r.strip())


def inputs_digest(inputs: list[str]) -> str:
    canonical = "\n".join(inputs) + "\n"
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def read_lock_digest(lock_path: Path) -> str | None:
    if not lock_path.is_file():
        return None
    for line in lock_path.read_text(encoding="utf-8").splitlines():
        if line.startswith(INPUTS_HASH_PREFIX):
            return line[len(INPUTS_HASH_PREFIX):].strip()
    return None


def write_lock(pkg_dir: Path) -> Path:
    uv = shutil.which("uv")
    if not uv:
        sys.exit("uv is required for `lock` mode (https://docs.astral.sh/uv/)")
    inputs = lock_inputs(pkg_dir)
    lock_path = pkg_dir / LOCK_NAME
    with tempfile.TemporaryDirectory() as tmp:
        req_in = Path(tmp) / "requirements-build.in"
        req_in.write_text("\n".join(inputs) + "\n", encoding="utf-8")
        cmd = [
            uv, "pip", "compile", str(req_in),
            "--generate-hashes",
            "--python-version", PYTHON_VERSION,
            "--python-platform", PYTHON_PLATFORM,
            "--no-header",
            "--no-annotate",
            "--quiet",
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.exit(f"uv pip compile failed for {pkg_dir.name}:\n{result.stderr}")
    header = [
        f"# Hash-locked build environment for {pkg_dir.name}.",
        "# Generated by: python .github/scripts/lock_build_env.py lock " + pkg_dir.name,
        f"# Target: CPython {PYTHON_VERSION} on {PYTHON_PLATFORM} (the publish workflow runner).",
        "# Install with: pip install --require-hashes -r requirements-build.lock",
        "# Do not edit by hand; regenerate when pyproject.toml changes.",
        INPUTS_HASH_PREFIX + inputs_digest(inputs),
        "# inputs:",
        *[f"#   {r}" for r in inputs],
        "",
    ]
    lock_path.write_text("\n".join(header) + result.stdout, encoding="utf-8")
    return lock_path


def check_inputs(pkg_dir: Path) -> str | None:
    """Return an error string if the lock is missing or stale, else None."""
    lock_path = pkg_dir / LOCK_NAME
    recorded = read_lock_digest(lock_path)
    if recorded is None:
        return f"{pkg_dir.name}: {LOCK_NAME} missing or has no {INPUTS_HASH_PREFIX.strip()} line"
    expected = inputs_digest(lock_inputs(pkg_dir))
    if recorded != expected:
        return (
            f"{pkg_dir.name}: {LOCK_NAME} is stale (pyproject inputs changed); "
            f"run: python .github/scripts/lock_build_env.py lock {pkg_dir.name}"
        )
    text = lock_path.read_text(encoding="utf-8")
    if "--hash=sha256:" not in text:
        return f"{pkg_dir.name}: {LOCK_NAME} contains no hashes"
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("mode", choices=("lock", "check-inputs"))
    parser.add_argument("packages", nargs="*", help="package directory names under packages/python/")
    parser.add_argument("--all", action="store_true", help="operate on every package")
    args = parser.parse_args(argv)
    if bool(args.packages) == args.all:
        parser.error("give package names or --all, not both and not neither")
    dirs = package_dirs(None if args.all else args.packages)

    if args.mode == "lock":
        for d in dirs:
            path = write_lock(d)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
        return 0

    errors = [e for e in (check_inputs(d) for d in dirs) if e]
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    print(f"checked {len(dirs)} package(s): {len(dirs) - len(errors)} ok, {len(errors)} failing")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
