"""HMAC message signing utilities for the coordination bus.

This module provides standalone signing functions and verification
utilities that can be used independently of the BusIdentity class.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import threading
import time
from typing import Any


def generate_secret() -> bytes:
    """Generate a cryptographically secure 32-byte secret.

    Returns:
    -------
    bytes
        32 random bytes suitable for HMAC-SHA256
    """
    return secrets.token_bytes(32)


def sign_payload(
    secret: bytes,
    timestamp: str,
    sender: str,
    recipient: str,
    msg_type: str,
    payload: dict[str, Any],
    nonce: str,
) -> str:
    """Create HMAC-SHA256 signature for message components.

    Parameters
    ----------
    secret : bytes
        Secret key for signing
    timestamp : str
        ISO 8601 timestamp
    sender : str
        Sender identity ID
    recipient : str
        Recipient identity ID
    msg_type : str
        Message type
    payload : dict
        Message payload (will be JSON-encoded)
    nonce : str
        Unique nonce

    Returns:
    -------
    str
        Hex-encoded HMAC-SHA256 signature
    """
    # Canonical form: deterministic, sorted JSON
    canonical_payload = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )

    canonical = (
        f"{timestamp}|{sender}|{recipient}|{msg_type}|{canonical_payload}|{nonce}"
    )

    return hmac.new(
        secret,
        canonical.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()


def verify_signature(
    secret: bytes,
    timestamp: str,
    sender: str,
    recipient: str,
    msg_type: str,
    payload: dict[str, Any],
    nonce: str,
    signature: str,
) -> bool:
    """Verify HMAC-SHA256 signature.

    Parameters
    ----------
    secret : bytes
        Secret key for verification
    timestamp : str
        ISO 8601 timestamp
    sender : str
        Sender identity ID
    recipient : str
        Recipient identity ID
    msg_type : str
        Message type
    payload : dict
        Message payload
    nonce : str
        Unique nonce
    signature : str
        Expected signature (hex)

    Returns:
    -------
    bool
        True if signature is valid
    """
    expected = sign_payload(
        secret, timestamp, sender, recipient, msg_type, payload, nonce
    )
    return hmac.compare_digest(expected, signature)


def unwrap_signing_envelope(message: str) -> str:
    """Unwrap ASI07 signing envelope if present.

    The bus_writer wraps messages in ``{"c": <content>, "n": <nonce>, "s": <sig>}``.
    This extracts the original content string.  If the message is not a
    signing envelope (plain text or different JSON shape), it is returned
    unchanged.

    Parameters
    ----------
    message : str
        Raw message string from the 5th TSV column of the coordination bus.

    Returns:
    -------
    str
        The unwrapped content, or the original message if no envelope.
    """
    try:
        data = json.loads(message)
        if isinstance(data, dict) and "c" in data and "n" in data and "s" in data:
            return data["c"]
    except (json.JSONDecodeError, TypeError):
        pass
    return message


def extract_timestamp_from_nonce(nonce: str) -> float | None:
    """Extract the timestamp embedded in a nonce.

    Parameters
    ----------
    nonce : str
        Nonce generated by generate_nonce()

    Returns:
    -------
    float | None
        Unix timestamp (seconds) or None if invalid format
    """
    try:
        millis_part = nonce.split("-")[0]
        return int(millis_part) / 1000
    except (ValueError, IndexError):
        return None


class NonceTracker:
    """Thread-safe nonce tracker for replay attack prevention.

    This tracker maintains a sliding window of seen nonces with
    automatic expiration. It's designed for single-threaded use
    within one identity context.
    """

    def __init__(self, ttl_seconds: float = 300.0, max_size: int = 10000):
        """Initialize nonce tracker.

        Parameters
        ----------
        ttl_seconds : float
            Time-to-live for nonce entries (seconds)
        max_size : int
            Maximum number of nonces to track before forced cleanup
        """
        self.ttl_seconds = ttl_seconds
        self.max_size = max_size
        self._seen: dict[str, float] = {}
        self._last_cleanup = time.time()
        self._lock = threading.Lock()  # Add a lock

    def _cleanup(self) -> None:
        """Remove expired nonces."""
        with self._lock:  # Acquire lock for _seen access
            now = time.time()
            if now - self._last_cleanup < 60:  # At most once per minute
                return

            cutoff = now - self.ttl_seconds
            expired = [n for n in self._seen if self._seen[n] < cutoff]
            for nonce in expired:
                del self._seen[nonce]

            self._last_cleanup = now

    def is_replay(self, nonce: str) -> bool:
        """Check if nonce is a replay and record it.

        Parameters
          ----------
        nonce : str
            Nonce to check

        Returns:
        -------
        bool
            True if nonce was previously seen (replay detected)
        """
        self._cleanup()  # Cleanup can acquire its own lock

        with self._lock:  # Acquire lock for _seen access
            # Check memory limit
            if len(self._seen) >= self.max_size:
                # Remove oldest 10%
                sorted_items = sorted(self._seen.items(), key=lambda x: x[1])
                for old_nonce, _ in sorted_items[: self.max_size // 10]:
                    del self._seen[old_nonce]

            now = time.time()

            # Also check nonce's embedded timestamp for expiration
            nonce_ts = extract_timestamp_from_nonce(nonce)
            if nonce_ts and now - nonce_ts > self.ttl_seconds:
                # Nonce is too old by its own timestamp, treat as replay
                return True

            if nonce in self._seen:
                return True

            self._seen[nonce] = now
            return False

    def record(self, nonce: str) -> None:
        """Record a nonce as seen without checking.

        Use this after successful verification.

        Parameters
          ----------
        nonce : str
            Nonce to record
        """
        self._cleanup()  # Cleanup can acquire its own lock
        with self._lock:  # Acquire lock for _seen access
            self._seen[nonce] = time.time()

    def clear(self) -> None:
        """Clear all recorded nonces."""
        with self._lock:  # Acquire lock for _seen access
            self._seen.clear()
