# Copyright 2024-2026 HUMMBL, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Build docs/coverage/EVIDENCE_VALIDATION.{json,md} from current matrices.

Stdlib-only. Run from repo root:

    python scripts/build_evidence_validation_report.py

Outputs:
  - docs/coverage/EVIDENCE_VALIDATION.json — machine-readable, full per-row detail
  - docs/coverage/EVIDENCE_VALIDATION.md   — human-readable summary report

The validator is `hummbl_governance.compliance_mapper._validate_matrix`. This
script is the convenience entry point that runs validation across every
matrix file in `docs/coverage/` and emits aggregate + per-matrix reports.
"""
from __future__ import annotations

import datetime as _dt
import glob
import io
import json
import os
import sys
from pathlib import Path


def _repo_relative_posix(path: str | Path, repo_root: Path) -> str:
    """Return repo-relative paths with stable POSIX separators."""
    return Path(path).relative_to(repo_root).as_posix()


def main() -> int:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from hummbl_governance.compliance_mapper import _validate_matrix

    repo_root = Path.cwd().resolve()
    coverage_dir = repo_root / "docs" / "coverage"
    if not coverage_dir.is_dir():
        print(f"ERROR: {coverage_dir} not found; run from repo root.", file=sys.stderr)
        return 2

    results: dict[str, dict] = {}
    for path_str in sorted(glob.glob(str(coverage_dir / "*.md"))):
        fname = os.path.basename(path_str)
        if fname == "README.md" or fname == "EVIDENCE_VALIDATION.md":
            continue
        buf = io.StringIO()
        saved_stdout = sys.stdout
        sys.stdout = buf
        try:
            _validate_matrix(_repo_relative_posix(path_str, repo_root), repo_root=str(repo_root), json_output=True)
        finally:
            sys.stdout = saved_stdout
        data = json.loads(buf.getvalue())
        results[fname] = data

    json_path = coverage_dir / "EVIDENCE_VALIDATION.json"
    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2, ensure_ascii=False)
    print(f"WROTE {json_path}")

    # Aggregates
    total_ful = sum(d["totals"]["fulfilled"] for d in results.values())
    total_validated = sum(d["fulfilled_validation"]["rows_passed"] for d in results.values())
    total_failed = sum(d["fulfilled_validation"]["rows_failed"] for d in results.values())
    total_no_refs = sum(d["fulfilled_validation"]["rows_without_refs"] for d in results.values())
    pct = round(100.0 * total_validated / total_ful, 1) if total_ful else 0.0

    today = _dt.date.today().isoformat()

    lines: list[str] = []
    lines.append("# Evidence Validation Report — HUMMBL Coverage Matrices")
    lines.append("")
    lines.append(
        "Generated by `python -m hummbl_governance.compliance_mapper --validate <matrix.md>`"
    )
    lines.append(
        "Source: `hummbl_governance/compliance_mapper.py` — `_validate_matrix`, `_parse_matrix_rows`, `_extract_refs`, `_resolve_evidence`"  # noqa: E501
    )
    lines.append("")
    lines.append("## Purpose")
    lines.append("")
    lines.append(
        "For each Fulfilled row in every coverage matrix, the validator extracts backtick-quoted file/path references in the Evidence and Coverage cells, then resolves each reference against the package layout (with legacy hummbl-governance alias support). A row is **validated** only when ALL of its evidence refs resolve to an existing artifact or a documented Tier-2/EXTERNAL marker."  # noqa: E501
    )
    lines.append("")
    lines.append(
        "Per [ADR-001](./../adr/ADR-001-coverage-matrix-not-self-grade.md), Fulfilled rows are public claim support ONLY when their Evidence column points to a validated runnable command or resolvable artifact. Rows without resolved evidence remain DRAFT until hardened."  # noqa: E501
    )
    lines.append("")
    lines.append(f"## Aggregate (as of {today})")
    lines.append("")
    lines.append(f"- **{total_ful} Fulfilled rows** across {len(results)} matrices")
    lines.append(f"- **{total_validated} rows validated** ({pct}%) — refs fully resolve")
    lines.append(f"- **{total_failed} rows fail validation** — hardening gap")
    lines.append(
        f"- **{total_no_refs} rows carry NO evidence references** at all (subset of failing)"
    )
    lines.append("")
    lines.append(
        "Status: matrices remain DRAFT SCAFFOLDS per `docs/coverage/README.md`; this report quantifies the residual hardening work."  # noqa: E501
    )
    lines.append("")
    lines.append("## Per-matrix summary")
    lines.append("")
    lines.append("| Matrix | Fulfilled | Validated | Coverage | No Refs |")
    lines.append("|---|---:|---:|---:|---:|")
    for fname in sorted(results):
        d = results[fname]
        f = d["totals"]["fulfilled"]
        p = d["fulfilled_validation"]["rows_passed"]
        nr = d["fulfilled_validation"]["rows_without_refs"]
        pcent = d["fulfilled_validation"]["coverage_pct"]
        lines.append(f"| [`{fname}`](./{fname}) | {f} | {p} | {pcent}% | {nr} |")
    lines.append(
        f"| **TOTAL** | **{total_ful}** | **{total_validated}** | **{pct}%** | **{total_no_refs}** |"
    )
    lines.append("")
    lines.append("## How to harden a row")
    lines.append("")
    lines.append("A Fulfilled row currently failing validation can be hardened by ONE of:")
    lines.append("")
    lines.append(
        "1. **Add an Evidence reference** — backtick-quote a file path (e.g., `` `hummbl_governance/kill_switch.py` ``) or command (e.g., `` `compliance_mapper --framework eu-ai-act --export annex-iv` ``) in the row's Evidence column."  # noqa: E501
    )
    lines.append(
        "2. **Update legacy reference** — if the row cites a hummbl-governance-layout path like `services/kill_switch_core.py`, either (a) update it to the canonical hummbl-governance path (`hummbl_governance/kill_switch.py`), or (b) add the legacy mapping to `_MODULE_ALIASES` in `compliance_mapper.py`."  # noqa: E501
    )
    lines.append(
        "3. **Downgrade the row** — if the primitive does not yet exist as shipped code, change the state glyph from Fulfilled to Partial with the missing-half named."  # noqa: E501
    )
    lines.append(
        "4. **Mark as Tier-2/External** — if the evidence is an admitted dependency (e.g., `services/c2pa_mcp`) or lives in another repo (e.g., `_state/coordination/messages.tsv` from hummbl-governance), use the existing `_MODULE_ALIASES` markers `TIER2_ADMITTED:` / `EXTERNAL:`."  # noqa: E501
    )
    lines.append("")
    lines.append("After hardening, re-run validation:")
    lines.append("")
    lines.append("```bash")
    lines.append("python -m hummbl_governance.compliance_mapper --validate docs/coverage/<matrix>.md")
    lines.append("python scripts/build_evidence_validation_report.py")
    lines.append("```")
    lines.append("")
    lines.append("## Failing rows by matrix")
    lines.append("")
    for fname in sorted(results):
        d = results[fname]
        failing = [r for r in d["rows"] if r["status"] == "fail"]
        if not failing:
            continue
        lines.append(f"### {fname}")
        lines.append("")
        lines.append("| Line | Control | Status | Detail |")
        lines.append("|---:|---|---|---|")
        for r in failing[:30]:
            cid = r["control_id"].replace("|", r"\|")[:50]
            detail = r["detail"].replace("|", r"\|")[:80]
            lines.append(f"| {r['line_no']} | {cid} | fail | {detail} |")
        if len(failing) > 30:
            lines.append(
                f"| ... | (+{len(failing) - 30} more rows) | | see EVIDENCE_VALIDATION.json |"
            )
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Re-generating this report")
    lines.append("")
    lines.append("```bash")
    lines.append("python scripts/build_evidence_validation_report.py")
    lines.append("```")

    md_path = coverage_dir / "EVIDENCE_VALIDATION.md"
    with md_path.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"WROTE {md_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
