/**
 * Cross-language conformance test for HUMMBL Tuple canonical serialization.
 *
 * Reads conformance_vectors.jsonl (generated by the Python reference) and
 * verifies that the TypeScript implementation produces byte-identical output.
 *
 * Run: npx tsx reference_impl/typescript/conformance_test.ts
 */

import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalJson, contentHash } from './tuple.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const vectorsPath = join(__dirname, '..', 'conformance_vectors.jsonl');

interface Vector {
  name: string;
  canonical_json: string;
  content_hash: string;
}

interface TestCase {
  name: string;
  tuple: Record<string, unknown>;
}

const testCases: TestCase[] = [
  {
    name: 'minimal contract tuple',
    tuple: {
      tuple_type: 'CONTRACT',
      id: '00000000-0000-0000-0000-000000000001',
      time: '2026-01-01T00:00:00Z',
      tuple_data: {
        contract_id: 'ctr-001',
        scope: 'test-scope',
        constraints: { max_cost: 100, max_duration: 3600 },
      },
    },
  },
  {
    name: 'tuple with float values',
    tuple: {
      tuple_type: 'EVIDENCE',
      id: '00000000-0000-0000-0000-000000000002',
      time: '2026-01-01T00:00:01Z',
      tuple_data: {
        drift: 0.75,
        confidence: 0.5,
        agent: 'test-agent',
      },
    },
  },
  {
    name: 'tuple with non-ASCII text',
    tuple: {
      tuple_type: 'SYSTEM',
      id: '00000000-0000-0000-0000-000000000003',
      time: '2026-01-01T00:00:02Z',
      tuple_data: {
        event: 'startup',
        notes: 'café — naïve résumé',
        agent: 'test-agent',
      },
    },
  },
  {
    name: 'tuple with nested objects and arrays',
    tuple: {
      tuple_type: 'MODEL_SELECTED',
      id: '00000000-0000-0000-0000-000000000004',
      time: '2026-01-01T00:00:03Z',
      tuple_data: {
        selection_rationale: 'best fit',
        alternatives_considered: ['model-a', 'model-b', 'model-c'],
        metadata: { tier: 1, tags: ['fast', 'cheap'] },
      },
    },
  },
  {
    name: 'tuple with null values (should be omitted)',
    tuple: {
      tuple_type: 'EVIDENCE',
      id: '00000000-0000-0000-0000-000000000005',
      time: '2026-01-01T00:00:04Z',
      tuple_data: {
        agent: 'test-agent',
        notes: null,
        optional_field: undefined,
        required_field: 'present',
      },
    },
  },
  {
    name: 'tuple with integrity fields (should be excluded from hash)',
    tuple: {
      tuple_type: 'EVIDENCE',
      id: '00000000-0000-0000-0000-000000000006',
      time: '2026-01-01T00:00:05Z',
      tuple_data: {
        agent: 'test-agent',
        previous_hash: 'abc123',
        args_hash: 'def456',
        signature: 'sig789',
      },
    },
  },
];

// Read Python-generated vectors
const vectorsContent = readFileSync(vectorsPath, 'utf-8');
const vectors: Vector[] = vectorsContent
  .trim()
  .split('\n')
  .map((line) => JSON.parse(line) as Vector);

const vectorMap = new Map(vectors.map((v) => [v.name, v]));

let passed = 0;
let failed = 0;

for (const tc of testCases) {
  const vector = vectorMap.get(tc.name);
  if (!vector) {
    console.error(`FAIL: ${tc.name} — no Python vector found`);
    failed++;
    continue;
  }

  const tsCanonical = canonicalJson(tc.tuple);
  const tsHash = contentHash(tc.tuple as any);

  const canonicalMatch = tsCanonical === vector.canonical_json;
  const hashMatch = tsHash === vector.content_hash;

  if (canonicalMatch && hashMatch) {
    console.log(`PASS: ${tc.name}`);
    console.log(`  canonical: ${tsCanonical}`);
    console.log(`  hash:      ${tsHash}`);
    passed++;
  } else {
    console.error(`FAIL: ${tc.name}`);
    if (!canonicalMatch) {
      console.error(`  canonical mismatch:`);
      console.error(`    Python: ${vector.canonical_json}`);
      console.error(`    TS:     ${tsCanonical}`);
    }
    if (!hashMatch) {
      console.error(`  hash mismatch:`);
      console.error(`    Python: ${vector.content_hash}`);
      console.error(`    TS:     ${tsHash}`);
    }
    failed++;
  }
}

console.log(`\n${passed}/${passed + failed} tests passed`);
process.exit(failed > 0 ? 1 : 0);
