#!/usr/bin/env python3
"""Reject AI authorship fingerprints in commit metadata.

This linter intentionally scans commit metadata, not source files. HUMMBL
permits internal receipts to record AI assistance, but Git commit metadata must
remain a human-authored project record.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


BLOCKED_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "ai-coauthor-trailer",
        re.compile(
            r"(?im)^co-authored-by:\s*.*\b("
            r"ai|agent|bot|codex|claude|devin|copilot|gemini|openai|anthropic|"
            r"cognition|cursor|windsurf"
            r")\b"
        ),
    ),
    (
        "generated-by-trailer",
        re.compile(
            r"(?im)^(generated-by|authored-with|authored-by|created-with):\s*.+"
        ),
    ),
    (
        "ai-credit-line",
        re.compile(
            r"(?im)\b("
            r"generated by|authored by|co-authored by|implemented by|written by"
            r")\s+("
            r"ai|agent|bot|codex|claude|devin|copilot|gemini|openai|anthropic|"
            r"cognition|cursor|windsurf"
            r")\b"
        ),
    ),
)

BLOCKED_IDENTITY_PATTERN = re.compile(
    r"\b("
    r"ai|agent|bot|codex|claude|devin|copilot|gemini|openai|anthropic|"
    r"cognition|cursor|windsurf"
    r")\b",
    re.IGNORECASE,
)

# Deterministic allowlist: only these identities may author/commit on the
# hummbl-dev account. Any identity not in this set is blocked regardless of
# whether it matches the blocklist above. The allowlist is stricter than the
# blocklist — it makes the rule deterministic (closed by default) rather than
# pattern-based (open by default).
ALLOWED_IDENTITIES: tuple[tuple[str, str], ...] = (
    ("hummbl-dev", "noreply@hummbl.dev"),
)


@dataclass(frozen=True)
class Finding:
    rule: str
    line: int
    text: str


def lint_text(text: str) -> list[Finding]:
    findings: list[Finding] = []
    for rule, pattern in BLOCKED_PATTERNS:
        for match in pattern.finditer(text):
            line = text.count("\n", 0, match.start()) + 1
            line_text = text.splitlines()[line - 1] if text.splitlines() else ""
            findings.append(Finding(rule=rule, line=line, text=line_text.strip()))
    return findings


def _parse_git_ident(text: str) -> tuple[str, str] | None:
    """Parse a ``git var GIT_*_IDENT`` string into (name, email).

    The format is ``Name <email> timestamp tz``. Returns None if parsing fails.
    """
    match = re.match(r"^(.*?)\s+<([^>]+)>", text)
    if not match:
        return None
    return match.group(1), match.group(2)


def lint_identity_text(text: str, *, label: str) -> list[Finding]:
    """Lint a Git identity string such as ``git var GIT_AUTHOR_IDENT``.

    Two checks run in order:
    1. Blocklist: rejects identities matching known AI/agent/vendor names.
    2. Allowlist: rejects any identity not in ``ALLOWED_IDENTENCIES``.

    The allowlist is deterministic and stricter — it catches identities
    that the blocklist would miss (e.g., a new agent name not yet in the
    blocklist, or a personal account that does not match any blocklist term).
    """
    findings: list[Finding] = []
    if BLOCKED_IDENTITY_PATTERN.search(text):
        findings.append(Finding(rule=f"ai-{label}-identity", line=1, text=text.strip()))
    parsed = _parse_git_ident(text)
    if parsed is not None:
        name, email = parsed
        if (name, email) not in ALLOWED_IDENTITIES:
            findings.append(
                Finding(
                    rule=f"identity-not-allowlisted-{label}",
                    line=1,
                    text=f"{name} <{email}> (allowed: {ALLOWED_IDENTITIES})",
                )
            )
    return findings


def _git_identity(var_name: str) -> str:
    result = subprocess.run(
        ["git", "var", var_name],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git var {var_name} failed")
    return result.stdout.strip()


def lint_effective_git_identities() -> list[Finding]:
    """Lint effective Git author and committer identities for this commit."""
    findings: list[Finding] = []
    findings.extend(lint_identity_text(_git_identity("GIT_AUTHOR_IDENT"), label="author"))
    findings.extend(
        lint_identity_text(_git_identity("GIT_COMMITTER_IDENT"), label="committer")
    )
    return findings


def _commit_messages_from_range(commit_range: str) -> str:
    result = subprocess.run(
        ["git", "log", "--format=%B%n---HUMMBL-COMMIT-END---", commit_range],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "git log failed")
    return result.stdout


def _read_input(args: argparse.Namespace) -> str:
    if args.commit_msg_file:
        return Path(args.commit_msg_file).read_text(encoding="utf-8")
    if args.range:
        return _commit_messages_from_range(args.range)
    if not sys.stdin.isatty():
        return sys.stdin.read()
    raise RuntimeError("provide a commit message file, --range, or stdin")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("commit_msg_file", nargs="?")
    parser.add_argument(
        "--check-identity",
        action="store_true",
        help="also reject effective Git author/committer identities that name AI agents",
    )
    parser.add_argument(
        "--range",
        help="Git revision range to scan, e.g. origin/main..HEAD",
    )
    args = parser.parse_args(argv)

    try:
        text = _read_input(args)
    except Exception as exc:
        print(f"provenance-lint: {exc}", file=sys.stderr)
        return 2

    findings = lint_text(text)
    if args.check_identity:
        try:
            findings.extend(lint_effective_git_identities())
        except Exception as exc:
            print(f"provenance-lint: {exc}", file=sys.stderr)
            return 2
    if not findings:
        return 0

    print(
        "ERROR: AI authorship attribution is not allowed in HUMMBL commit "
        "metadata.",
        file=sys.stderr,
    )
    for finding in findings:
        print(
            f"  {finding.rule}: line {finding.line}: {finding.text}",
            file=sys.stderr,
        )
    print(
        "Record AI assistance in internal receipts or PR notes, not commit "
        "authorship trailers.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
