#!/usr/bin/env python3
"""Crawl live provider /models endpoints to verify and extend the registry.

For each provider that has a models_endpoint, this script:
  1. Fetches the list of available models from the live API
  2. Matches each live model against the curated registry entries
  3. Marks matched entries as verified=True
  4. Discovers models not in the curated taxonomy and adds them as
     source="crawler" entries (the "morning axis extension")

Requires API keys in environment variables. Providers without keys are
skipped with a warning.

Usage:
    python tools/crawl.py                    # crawl all providers with keys
    python tools/crawl.py --provider groq    # crawl one provider
    python tools/crawl.py --dry-run          # list what would be crawled, don't fetch
    python tools/crawl.py --stats            # print verification statistics
"""

import argparse
import json
import os
import re
import sys
import urllib.request
import urllib.error
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8")

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
REGISTRY_DIR = REPO_ROOT / "registry"


def load_yaml(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_registry():
    registry_file = REGISTRY_DIR / "registry.json"
    if registry_file.exists():
        with open(registry_file, encoding="utf-8") as f:
            return json.load(f)
    return []


def save_registry(entries):
    REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
    registry_file = REGISTRY_DIR / "registry.json"
    with open(registry_file, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)

    # Also update TypeScript export
    ts_file = REGISTRY_DIR / "registry.ts"
    with open(ts_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/generate.py + tools/crawl.py — do not edit by hand.\n")
        f.write(f"// {len(entries)} model-provider pairs.\n\n")
        f.write("export interface ModelEntry {\n")
        f.write("  id: string;\n  label: string;\n  family: string;\n")
        f.write("  family_name: string;\n  vendor: string;\n  license: string;\n")
        f.write("  size_b: number;\n  variant: string;\n  variant_desc: string;\n")
        f.write("  provider: string;\n  provider_name: string;\n  api_compat: string;\n")
        f.write("  endpoint: string;\n  model_slug: string;\n  api_key_env: string;\n")
        f.write("  api_key_url: string;\n  free_tier_type: string;\n")
        f.write("  free_tier_rate_limit: string;\n  requires_cc: boolean;\n")
        f.write("  multimodal: boolean;\n  function_calling: boolean;\n")
        f.write("  search_grounding: boolean;\n  streaming: boolean;\n")
        f.write("  reasoning: boolean;\n  code_specialized: boolean;\n")
        f.write("  context_window: number;\n  cost_note: string;\n")
        f.write("  source: string;\n  verified: boolean;\n}\n\n")
        f.write("export const REGISTRY: ModelEntry[] = ")
        f.write(json.dumps(entries, indent=2, ensure_ascii=False))
        f.write(";\n")


def fetch_json(url, api_key=None, timeout=15):
    """Fetch JSON from a URL with optional Bearer auth."""
    req = urllib.request.Request(url)
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        return {"_error": f"HTTP {e.code}: {e.reason}"}
    except urllib.error.URLError as e:
        return {"_error": f"URL error: {e.reason}"}
    except Exception as e:
        return {"_error": str(e)}


# -- provider-specific model list parsers --------------------------------

def parse_models_response(provider_id, data):
    """Parse the /models response into a list of model slugs.

    Different providers return different JSON shapes. This handles the
    common ones: OpenAI-compatible (data: [{id: ...}]), and custom.
    """
    if "_error" in data:
        return [], data["_error"]

    # OpenAI-compatible: {"data": [{"id": "model-slug", ...}, ...]}
    if isinstance(data, dict) and "data" in data:
        models = []
        for item in data["data"]:
            if isinstance(item, dict) and "id" in item:
                models.append(item["id"])
            elif isinstance(item, str):
                models.append(item)
        return models, None

    # Some providers return a bare list
    if isinstance(data, list):
        models = []
        for item in data:
            if isinstance(item, dict) and "id" in item:
                models.append(item["id"])
            elif isinstance(item, str):
                models.append(item)
        return models, None

    # Google AI Studio: {"models": [{"name": "models/gemini-...", ...}, ...]}
    if isinstance(data, dict) and "models" in data:
        models = []
        for item in data["models"]:
            if isinstance(item, dict):
                name = item.get("name", item.get("id", ""))
                # Strip "models/" prefix
                name = name.replace("models/", "")
                models.append(name)
        return models, None

    return [], f"Unknown response shape: {list(data.keys()) if isinstance(data, dict) else type(data)}"


def is_free_model(provider, model_slug):
    """Determine if a model is free based on the provider's free_filter rule."""
    rule = provider.get("free_filter", "all")
    slug_lower = model_slug.lower()

    if rule == "all":
        return True
    elif rule == "suffix_free":
        return slug_lower.endswith(":free")
    elif rule == "zero_price":
        # Would need pricing data from the API — assume free for now
        return True
    elif rule == "flash_models":
        return "flash" in slug_lower
    elif rule == "small_models":
        # HuggingFace: free for <10B param models
        return True  # conservative — verify via API metadata
    elif rule == "free_tier_models":
        return True  # Ollama — would need to check against free tier list
    elif rule == "n/a":
        return False
    else:
        return True


# -- matching logic ------------------------------------------------------

def match_to_registry(live_slug, provider_id, registry_entries):
    """Match a live model slug to a registry entry.

    Tries (in order):
      1. Exact slug match
      2. Partial slug containment
      3. Keyword match: family + size + variant keywords in the live slug
    """
    live_lower = live_slug.lower()

    # 1. Exact match on model_slug
    for entry in registry_entries:
        if entry["provider"] == provider_id and entry["model_slug"] == live_slug:
            return entry

    # 2. Partial match: the live slug contains the registry slug or vice versa
    for entry in registry_entries:
        if entry["provider"] != provider_id:
            continue
        reg_slug = entry["model_slug"].lower()
        if live_lower in reg_slug or reg_slug in live_lower:
            return entry

    # 3. Keyword match: family + size + variant all present in the live slug
    live_family = infer_family_from_slug(live_slug)
    live_size = infer_size_from_slug(live_slug)
    live_variant = infer_variant_from_slug(live_slug)

    if live_family and live_size > 0:
        candidates = []
        for entry in registry_entries:
            if entry["provider"] != provider_id:
                continue
            if entry["family"] != live_family:
                continue
            if entry["size_b"] != live_size:
                continue
            # Variant doesn't need to match exactly — the closest is fine
            score = 0
            if entry["variant"] == live_variant:
                score += 3
            elif entry["variant"] in ("instruct", "chat", "base"):
                score += 1
            candidates.append((score, entry))

        if candidates:
            candidates.sort(key=lambda x: -x[0])
            return candidates[0][1]

    return None


def infer_family_from_slug(slug):
    """Best-effort family inference from a model slug."""
    slug_lower = slug.lower()
    family_patterns = [
        ("llama", r"llama"),
        ("qwen", r"qwen"),
        ("gemma", r"gemma"),
        ("gemini", r"gemini"),
        ("mistral", r"mistral|codestral|pixtral|nemo"),
        ("deepseek", r"deepseek"),
        ("nemotron", r"nemotron"),
        ("gpt-oss", r"gpt-oss|gptoss"),
        ("command-r", r"command-r|command_r"),
        ("phi", r"phi-"),
        ("glm", r"glm"),
        ("yi", r"\byi-"),
        ("lfm", r"lfm-|liquid"),
        ("dbrx", r"dbrx"),
        ("north", r"north"),
    ]
    for family_id, pattern in family_patterns:
        if re.search(pattern, slug_lower):
            return family_id
    return None


def infer_size_from_slug(slug):
    """Best-effort size inference from a model slug."""
    # Match patterns like "70b", "7b", "671b", "3.5b", "550b"
    match = re.search(r"(\d+(?:\.\d+)?)b\b", slug.lower())
    if match:
        return float(match.group(1))
    return 0


def infer_variant_from_slug(slug):
    """Best-effort variant inference from a model slug."""
    slug_lower = slug.lower()
    if any(v in slug_lower for v in ["vision", "vl", "pixtral"]):
        return "vision"
    if any(v in slug_lower for v in ["reasoning", "r1", "qwq", "thinking"]):
        return "reasoning"
    if any(v in slug_lower for v in ["coder", "codestral", "code"]):
        return "code"
    if "instruct" in slug_lower:
        return "instruct"
    if "chat" in slug_lower:
        return "chat"
    if "flash" in slug_lower:
        return "flash"
    if "lite" in slug_lower:
        return "flash-lite"
    return "base"


# -- crawl ---------------------------------------------------------------

def crawl_provider(provider, registry_entries, dry_run=False):
    """Crawl one provider's /models endpoint."""
    endpoint = provider.get("models_endpoint")
    if not endpoint:
        return [], [], f"No models_endpoint for {provider['id']}"

    # Resolve account_id placeholder for Cloudflare
    if "{account_id}" in endpoint:
        account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
        if not account_id:
            return [], [], "CLOUDFLARE_ACCOUNT_ID not set"
        endpoint = endpoint.replace("{account_id}", account_id)

    api_key = os.environ.get(provider["api_key_env"], "")

    if dry_run:
        return [], [], None

    if not api_key and provider["free_tier"]["type"] != "permanent":
        return [], [], f"No API key ({provider['api_key_env']}) — skipping"

    print(f"  Crawling {provider['id']}...", end=" ", flush=True)
    data = fetch_json(endpoint, api_key=api_key if api_key else None)
    models, error = parse_models_response(provider["id"], data)

    if error:
        print(f"FAIL: {error}")
        return [], [], error

    # Filter to free models only
    free_models = [m for m in models if is_free_model(provider, m)]
    print(f"{len(models)} models found, {len(free_models)} free")

    # Match against registry
    verified_ids = set()
    discovered = []

    for slug in free_models:
        match = match_to_registry(slug, provider["id"], registry_entries)
        if match:
            verified_ids.add(match["id"])
        else:
            # Discover new model not in curated taxonomy
            family_id = infer_family_from_slug(slug)
            size = infer_size_from_slug(slug)
            variant = infer_variant_from_slug(slug)

            if family_id:
                entry = {
                    "id": f"{family_id}-{int(size) if size else 'unk'}b-{variant}-{provider['id']}",
                    "label": f"{family_id.title()} {int(size) if size else '?'}B {variant.title()} ({provider['name']})",
                    "family": family_id,
                    "family_name": family_id.title(),
                    "vendor": family_id,
                    "license": "unknown",
                    "size_b": size,
                    "variant": variant,
                    "variant_desc": f"Discovered from {provider['name']} /models endpoint",
                    "provider": provider["id"],
                    "provider_name": provider["name"],
                    "api_compat": provider["api_compat"],
                    "endpoint": f"{provider['api_base']}/chat/completions" if provider["api_compat"] == "openai" else provider["api_base"],
                    "model_slug": slug,
                    "api_key_env": provider["api_key_env"],
                    "api_key_url": provider["api_key_url"],
                    "free_tier_type": provider["free_tier"]["type"],
                    "free_tier_rate_limit": provider["free_tier"]["rate_limit"],
                    "requires_cc": provider["free_tier"]["requires_cc"],
                    "multimodal": variant == "vision",
                    "function_calling": provider["features"]["function_calling"],
                    "search_grounding": provider["features"]["search_grounding"],
                    "streaming": provider["features"]["streaming"],
                    "reasoning": variant == "reasoning",
                    "code_specialized": variant == "code",
                    "context_window": 128_000,
                    "cost_note": f"Free tier — {provider['free_tier']['rate_limit']}",
                    "source": "crawler",
                    "verified": True,
                }
                discovered.append(entry)

    return verified_ids, discovered, None


def crawl_all(providers_data, registry_entries, provider_filter=None, dry_run=False):
    """Crawl all providers (or one if filtered)."""
    all_verified = set()
    all_discovered = []
    errors = []

    for provider in providers_data["providers"]:
        if provider_filter and provider["id"] != provider_filter:
            continue

        verified_ids, discovered, error = crawl_provider(provider, registry_entries, dry_run)
        if error:
            errors.append((provider["id"], error))
        all_verified.update(verified_ids)
        all_discovered.extend(discovered)

    return all_verified, all_discovered, errors


def _sanitize_error_for_log(error):
    """Redact potentially sensitive values from error text before logging."""
    text = str(error)
    # Redact common secret-bearing key/value patterns.
    text = re.sub(
        r"(?i)\b(api[_\-\s]*key|password|passwd|token|secret|bearer)\b\s*[:=]\s*([^\s,;]+)",
        r"\1=<redacted>",
        text,
    )
    # Redact env var style credential identifiers (e.g. OPENAI_API_KEY).
    text = re.sub(
        r"\b[A-Z0-9_]*(API_KEY|TOKEN|PASSWORD|SECRET)[A-Z0-9_]*\b",
        "<redacted>",
        text,
    )
    return text


def main():
    ap = argparse.ArgumentParser(description="Crawl live provider /models endpoints")
    ap.add_argument("--provider", help="Crawl only this provider id")
    ap.add_argument("--dry-run", action="store_true", help="List what would be crawled, don't fetch")
    ap.add_argument("--stats", action="store_true", help="Print verification statistics")
    ap.add_argument("--no-save", action="store_true", help="Don't save the registry")
    args = ap.parse_args()

    providers_data = load_yaml(DATA_DIR / "providers.yaml")
    registry = load_registry()

    print(f"\n{'='*60}")
    print(f"  FREE MODEL CRAWLER")
    print(f"  Registry: {len(registry)} entries")
    print(f"  Providers: {len(providers_data['providers'])}")
    print(f"{'='*60}\n")

    verified_ids, discovered, errors = crawl_all(
        providers_data, registry, provider_filter=args.provider, dry_run=args.dry_run
    )

    # Mark verified entries
    for entry in registry:
        if entry["id"] in verified_ids:
            entry["verified"] = True

    # Add discovered entries (dedup by id)
    existing_ids = {e["id"] for e in registry}
    new_discovered = [e for e in discovered if e["id"] not in existing_ids]
    final = registry + new_discovered

    print(f"\n--- Results ---")
    print(f"  Verified:    {len(verified_ids)} entries")
    print(f"  Discovered:  {len(new_discovered)} new entries")
    print(f"  Errors:      {len(errors)} providers")
    if errors:
        for pid, err in errors:
            print(f"    {pid}: {_sanitize_error_for_log(err)}")
    print(f"  Total:       {len(final)} entries")

    if not args.no_save and not args.dry_run:
        save_registry(final)
        print(f"\n  Saved to: {REGISTRY_DIR / 'registry.json'}")

    if args.stats:
        print(f"\n--- Statistics ---")
        verified = sum(1 for e in final if e.get("verified"))
        by_source = {}
        by_provider = {}
        for e in final:
            by_source[e.get("source", "curated")] = by_source.get(e.get("source", "curated"), 0) + 1
            by_provider[e["provider"]] = by_provider.get(e["provider"], 0) + 1
        print(f"  Verified:  {verified}/{len(final)} ({100*verified//len(final) if final else 0}%)")
        print(f"  By source: {by_source}")
        print(f"  Top providers:")
        for p, c in sorted(by_provider.items(), key=lambda x: -x[1])[:10]:
            print(f"    {p:25s}  {c}")


if __name__ == "__main__":
    main()
